name: Notify Role

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  
jobs:
  notify:
    name: Notify Role
    runs-on: ubuntu-latest
    steps:
      - name: Notify Role
        env:
          SERVER_URL: ${{ secrets. SERVER_URL }}
        run: |
            curl -X POST -H "Content-Type: application/json" \
            -d '{
              "content": "<@1465277086863458457>",
              "allowed_mentions": {
                "roles": ["1465277086863458457"]
              }
            }' \
            $SERVER_URL